// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Pathician")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","23.07.2021")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Pathician"
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "23.07.2021"
