// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("PathfinderAttackSimulator")>]
[<assembly: AssemblyProductAttribute("PathfinderAttackSimulator")>]
[<assembly: AssemblyDescriptionAttribute("An automatic calculator for both standard and full round attack actions, based on a library of modifications, weapons and characters.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "PathfinderAttackSimulator"
    let [<Literal>] AssemblyProduct = "PathfinderAttackSimulator"
    let [<Literal>] AssemblyDescription = "An automatic calculator for both standard and full round attack actions, based on a library of modifications, weapons and characters."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
